### ISSUE TITLE
节假日信息的接口bug

### ISSUE THREAD

**Issue by fayeshine** [shidenggui/easyutils#4]
那个接口开始使用授权码了，作者去官网看吧，现在返回的是垃圾信息

**Comment by shidenggui** [comment]
日期这些接口其实手动整理下可以用很久， 我准备自建一个api用docker部署在阿里云，服务端用python / 或者 go 来写，开源在 github，一起维护

**Comment by shidenggui** [comment]
发现了一个百度apistore的免费版本，把现在用的替换了。当前 api 来自百度 apistore: http://apistore.baidu.com/apiworks/servicedetail/1116.html
